### ISSUE TITLE
elftools build exception on macOS ARM: `Magic number does not match`

### ISSUE THREAD

**Issue by antoineco** [inscapist/ruby-nix#47]
### What happened

While trying to use `ruby-nix` in a [Github Pages](https://rubygems.org/gems/github-pages) project on macOS (aarch64-darwin) I am consistently getting a build exception running `nix develop` after generating `gemset.nix`.

The [project's source tree](https://github.com/antoineco/antoineco.github.io/tree/ruby-nix), for reference.

<details><summary>:page_facing_up: Command output</summary>
<p>

```
error: builder for '/nix/store/z5w8imhq1pdvpc30pdb13ignxgv79v59-ruby3.3-ffi-1.17.0-arm64-darwin.drv' failed with exit code 1;
       last 25 log lines:
       > removed directory 'cache'
       > /private/tmp/nix-build-ruby3.3-ffi-1.17.0-arm64-darwin.drv-0
       > Running phase: fixupPhase
       > checking for references to /private/tmp/nix-build-ruby3.3-ffi-1.17.0-arm64-darwin.drv-0/ in /nix/store/an5bff2mhkvxlhm5myfrsw4znahp6jvi-ruby3.3-ffi-1.17.0-arm64-darwin...
       > patching script interpreter paths in /nix/store/an5bff2mhkvxlhm5myfrsw4znahp6jvi-ruby3.3-ffi-1.17.0-arm64-darwin
       > stripping (with command strip and flags -S) in  /nix/store/an5bff2mhkvxlhm5myfrsw4znahp6jvi-ruby3.3-ffi-1.17.0-arm64-darwin/lib /nix/store/an5bff2mhkvxlhm5myfrsw4znahp6jvi-ruby3.3-ffi-1.17.0-arm64-darwin/bin
       > rewriting symlink /nix/store/an5bff2mhkvxlhm5myfrsw4znahp6jvi-ruby3.3-ffi-1.17.0-arm64-darwin/nix-support/gem-meta/spec to be relative to /nix/store/an5bff2mhkvxlhm5myfrsw4znahp6jvi-ruby3.3-ffi-1.17.0-arm64-darwin
       > Traceback (most recent call last):
       >   File "/nix/store/5jah78jkphn4phk6msqf50kan5w0myn0-auto-patchelf.py", line 432, in <module>
       >     with open_elf(interpreter_path) as interpreter:
       >   File "/nix/store/75j38g8ii1nqkmpf6sdlj3s5dyah3gas-python3-3.12.5/lib/python3.12/contextlib.py", line 137, in __enter__
       >     return next(self.gen)
       >            ^^^^^^^^^^^^^^
       >   File "/nix/store/5jah78jkphn4phk6msqf50kan5w0myn0-auto-patchelf.py", line 27, in open_elf
       >     yield ELFFile(stream)
       >           ^^^^^^^^^^^^^^^
       >   File "/nix/store/8h58i3l5mxsl5g93ran0cs4c25pi14r4-python3-3.12.5-env/lib/python3.12/site-packages/elftools/elf/elffile.py", line 84, in __init__
       >     self._identify_file()
       >   File "/nix/store/8h58i3l5mxsl5g93ran0cs4c25pi14r4-python3-3.12.5-env/lib/python3.12/site-packages/elftools/elf/elffile.py", line 570, in _identify_file
       >     elf_assert(magic == b'\x7fELF', 'Magic number does not match')
       >   File "/nix/store/8h58i3l5mxsl5g93ran0cs4c25pi14r4-python3-3.12.5-env/lib/python3.12/site-packages/elftools/common/utils.py", line 80, in elf_assert
       >     _assert_with_exception(cond, msg, ELFError)
       >   File "/nix/store/8h58i3l5mxsl5g93ran0cs4c25pi14r4-python3-3.12.5-env/lib/python3.12/site-packages/elftools/common/utils.py", line 143, in _assert_with_exception
       >     raise exception_type(msg)
       > elftools.common.exceptions.ELFError: Magic number does not match
       For full logs, run 'nix log /nix/store/z5w8imhq1pdvpc30pdb13ignxgv79v59-ruby3.3-ffi-1.17.0-arm64-darwin.drv'.
error (ignored): error: cannot unlink '"/private/tmp/nix-build-ruby3.3-eventmachine-1.2.7.drv-5"': Directory not empty
error: 1 dependencies of derivation '/nix/store/6rwijnlxbdj39r7cnnj67g83wbcmrv8r-github-pages-ruby-env.drv' failed to build
error: 1 dependencies of derivation '/nix/store/y0h15b2c1n91rpa9kg0ldy3qpjdzp0rl-github-pages.drv' failed to build
error: 1 dependencies of derivation '/nix/store/0h9p9fny5sffiwi6dr5rxcxmlqni3wkb-nix-shell-env.drv' failed to build
```

</p>
</details>

<details><summary>:page_facing_up: Nix log</summary>
<p>

```
Running phase: unpackPhase
@nix { "action": "setPhase", "phase": "unpackPhase" }
Running phase: patchPhase
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: configurePhase
@nix { "action": "setPhase", "phase": "configurePhase" }
no configure script, doing nothing
Running phase: installPhase
@nix { "action": "setPhase", "phase": "installPhase" }
buildFlags:
WARNING:  You build with buildroot.
  Build root: /
  Bin dir: /nix/store/an5bff2mhkvxlhm5myfrsw4znahp6jvi-ruby3.3-ffi-1.17.0-arm64-darwin/lib/ruby/gems/3.3.0/bin
  Gem home: /nix/store/an5bff2mhkvxlhm5myfrsw4znahp6jvi-ruby3.3-ffi-1.17.0-arm64-darwin/lib/ruby/gems/3.3.0
  Plugins dir: /nix/store/an5bff2mhkvxlhm5myfrsw4znahp6jvi-ruby3.3-ffi-1.17.0-arm64-darwin/lib/ruby/gems/3.3.0/plugins
Successfully installed ffi-1.17.0-arm64-darwin
1 gem installed
/nix/store/an5bff2mhkvxlhm5myfrsw4znahp6jvi-ruby3.3-ffi-1.17.0-arm64-darwin/lib/ruby/gems/3.3.0 /private/tmp/nix-build-ruby3.3-ffi-1.17.0-arm64-darwin.drv-0
removed 'cache/ffi-1.17.0-arm64-darwin.gem'
removed directory 'cache'
/private/tmp/nix-build-ruby3.3-ffi-1.17.0-arm64-darwin.drv-0
Running phase: fixupPhase
@nix { "action": "setPhase", "phase": "fixupPhase" }
checking for references to /private/tmp/nix-build-ruby3.3-ffi-1.17.0-arm64-darwin.drv-0/ in /nix/store/an5bff2mhkvxlhm5myfrsw4znahp6jvi-ruby3.3-ffi-1.17.0-arm64-darwin...
patching script interpreter paths in /nix/store/an5bff2mhkvxlhm5myfrsw4znahp6jvi-ruby3.3-ffi-1.17.0-arm64-darwin
stripping (with command strip and flags -S) in  /nix/store/an5bff2mhkvxlhm5myfrsw4znahp6jvi-ruby3.3-ffi-1.17.0-arm64-darwin/lib /nix/store/an5bff2mhkvxlhm5myfrsw4znahp6jvi-ruby3.3-ffi-1.17.0-arm64-darwin/bin
rewriting symlink /nix/store/an5bff2mhkvxlhm5myfrsw4znahp6jvi-ruby3.3-ffi-1.17.0-arm64-darwin/nix-support/gem-meta/spec to be relative to /nix/store/an5bff2mhkvxlhm5myfrsw4znahp6jvi-ruby3.3-ffi-1.17.0-arm64-darwin
Traceback (most recent call last):
  File "/nix/store/5jah78jkphn4phk6msqf50kan5w0myn0-auto-patchelf.py", line 432, in <module>
    with open_elf(interpreter_path) as interpreter:
  File "/nix/store/75j38g8ii1nqkmpf6sdlj3s5dyah3gas-python3-3.12.5/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/nix/store/5jah78jkphn4phk6msqf50kan5w0myn0-auto-patchelf.py", line 27, in open_elf
    yield ELFFile(stream)
          ^^^^^^^^^^^^^^^
  File "/nix/store/8h58i3l5mxsl5g93ran0cs4c25pi14r4-python3-3.12.5-env/lib/python3.12/site-packages/elftools/elf/elffile.py", line 84, in __init__
    self._identify_file()
  File "/nix/store/8h58i3l5mxsl5g93ran0cs4c25pi14r4-python3-3.12.5-env/lib/python3.12/site-packages/elftools/elf/elffile.py", line 570, in _identify_file
    elf_assert(magic == b'\x7fELF', 'Magic number does not match')
  File "/nix/store/8h58i3l5mxsl5g93ran0cs4c25pi14r4-python3-3.12.5-env/lib/python3.12/site-packages/elftools/common/utils.py", line 80, in elf_assert
    _assert_with_exception(cond, msg, ELFError)
  File "/nix/store/8h58i3l5mxsl5g93ran0cs4c25pi14r4-python3-3.12.5-env/lib/python3.12/site-packages/elftools/common/utils.py", line 143, in _assert_with_exception
    raise exception_type(msg)
elftools.common.exceptions.ELFError: Magic number does not match
```

</p>
</details>

The issue may not originate from `ruby-nix` directly, but I wanted to report it here anyway in case something stands out from my setup.

### What I did

1. Created `flake.nix`
1. Ran `nix develop` _without `gemset.nix`_ -> this works
1. Ran `bundle-lock`
1. Ran `bundix`
1. Returned to parent shell (Ctrl-D)
1. Ran `git add .`

### Additional notes

The same error occurs with an unmodified flake generated by `nix flake init -t github:inscapist/ruby-nix/main`.

**Comment by antoineco** [comment]
Adding the detail of the problematic derivation for future references:

```console
$ nix derivation show /nix/store/z5w8imhq1pdvpc30pdb13ignxgv79v59-ruby3.3-ffi-1.17.0-arm64-darwin.drv
{
  "/nix/store/z5w8imhq1pdvpc30pdb13ignxgv79v59-ruby3.3-ffi-1.17.0-arm64-darwin.drv": {
    "args": [
      "-e",
      "/nix/store/v6x3cs394jgqfbi0a42pam708flxaphh-default-builder.sh"
    ],
    "builder": "/nix/store/ap4xjkwp0lshyywxqw88phnnc0j1fnzw-bash-5.2p32/bin/bash",
    "env": {
      "NIX_CFLAGS_COMPILE": "-fdeclspec",
      "__darwinAllowLocalNetworking": "",
      "__impureHostDeps": "/bin/sh /usr/lib/libSystem.B.dylib /usr/lib/system/libunc.dylib /dev/zero /dev/random /dev/urandom /bin/sh",
      "__propagatedImpureHostDeps": "",
      "__propagatedSandboxProfile": "",
      "__sandboxProfile": "",
      "__structuredAttrs": "",
      "buildInputs": "/nix/store/z115wn7gb17f6q32pv4a7rqw51czd14y-ruby-3.3.4 /nix/store/m4bdls4q3qaw6ay62365ai6skhvszpar-libobjc-11.0.0 /nix/store/l6kz17msxs83461bya1lq76n2y6n01jp-auto-patchelf-hook",
      "buildPhase": "runHook preBuild\n\nif [[ \"$gemType\" == \"gem\" ]]; then\n  if [[ -z \"$gemspec\" ]]; then\n    gemspec=\"$(find . -name '*.gemspec')\"\n    echo \"found the following gemspecs:\"\n    echo \"$gemspec\"\n    gemspec=\"$(echo \"$gemspec\" | head -n1)\"\n  fi\n\n  exec 3>&1\n  output=\"$(gem build $gemspec | tee >(cat - >&3))\"\n  exec 3>&-\n\n  gempkg=$(echo \"$output\" | grep -oP 'File: \\K(.*)')\n\n  echo \"gem package built: $gempkg\"\nelif [[ \"$gemType\" == \"git\" ]]; then\n  git init\n  # remove variations to improve the likelihood of a bit-reproducible output\n  rm -rf .git/logs/ .git/hooks/ .git/index .git/FETCH_HEAD .git/ORIG_HEAD .git/refs/remotes/origin/HEAD .git/config\n  # support `git ls-files`\n  git add .\nfi\n\nrunHook postBuild\n",
      "builder": "/nix/store/ap4xjkwp0lshyywxqw88phnnc0j1fnzw-bash-5.2p32/bin/bash",
      "cmakeFlags": "",
      "configureFlags": "",
      "dependencies": "",
      "depsBuildBuild": "",
      "depsBuildBuildPropagated": "",
      "depsBuildTarget": "",
      "depsBuildTargetPropagated": "",
      "depsHostHost": "",
      "depsHostHostPropagated": "",
      "depsTargetTarget": "",
      "depsTargetTargetPropagated": "",
      "doCheck": "",
      "doInstallCheck": "",
      "document": "",
      "dontBuild": "1",
      "dontStrip": "",
      "gemName": "ffi",
      "gemPath": "",
      "gemType": "gem",
      "groups": "default jekyll_plugins",
      "installPhase": "runHook preInstall\n\nexport GEM_HOME=$out/lib/ruby/gems/3.3.0\nmkdir -p $GEM_HOME\n\necho \"buildFlags: $buildFlags\"\n\n\n\n\nif [[ -z \"$gempkg\" ]]; then\n  echo \"failure: \\$gempkg path unspecified\" 1>&2\n  exit 1\nelif [[ ! -f \"$gempkg\" ]]; then\n  echo \"failure: \\$gempkg path invalid\" 1>&2\n  exit 1\nfi\n\ngem install \\\n  --local \\\n  --force \\\n  --http-proxy 'http://nodtd.invalid' \\\n  --ignore-dependencies \\\n  --install-dir \"$GEM_HOME\" \\\n  --build-root '/' \\\n  --backtrace \\\n  --no-env-shebang \\\n  -N \\\n  $gempkg $gemFlags -- $buildFlags\n\n# looks like useless files which break build repeatability and consume space\npushd $out/lib/ruby/gems/3.3.0\nfind doc/ -iname created.rid -delete -print\nfind gems/*/ext/ extensions/ \\( -iname Makefile -o -iname mkmf.log -o -iname gem_make.out \\) -delete -print\nrm -fvr cache\npopd\n\n# write out metadata and binstubs\nspec=$(echo $out/lib/ruby/gems/3.3.0/specifications/*.gemspec)\nruby /nix/store/qjj178v5f2afrzqkp6mvpzsyi1856mf3-gem-post-build.rb \"$spec\"\n\n\nfor section in {1..9}; do\n  mandir=\"$out/share/man/man$section\"\n  find $out/lib \\( -wholename \"*/man/*.$section\" -o -wholename \"*/man/man$section/*.$section\" \\) \\\n    -execdir mkdir -p $mandir \\; -execdir cp '{}' $mandir \\;\ndone\n\n\n# For Ruby-generated binstubs, shebang paths are already in Nix store but for\n# ruby used to build the package. Update them to match the host system. Note\n# that patchShebangsAuto ignores scripts where shebang line is already in Nix\n# store.\nif [[ -d $GEM_HOME/bin ]]; then\n  patchShebangs --update --host -- \"$GEM_HOME\"/bin\nfi\n\nrunHook postInstall\n",
      "mesonFlags": "",
      "name": "ruby3.3-ffi-1.17.0-arm64-darwin",
      "nativeBuildInputs": "/nix/store/z115wn7gb17f6q32pv4a7rqw51czd14y-ruby-3.3.4 /nix/store/s9kisphpd5vrxpgz97bkh0jgnazspdnq-make-shell-wrapper-hook",
      "out": "/nix/store/an5bff2mhkvxlhm5myfrsw4znahp6jvi-ruby3.3-ffi-1.17.0-arm64-darwin",
      "outputs": "out",
      "patches": "",
      "propagatedBuildInputs": "",
      "propagatedNativeBuildInputs": "",
      "propagatedUserEnvPkgs": "",
      "ruby": "/nix/store/z115wn7gb17f6q32pv4a7rqw51czd14y-ruby-3.3.4",
      "src": "/nix/store/i28040y8ka5yfcsybyidcbqlsmcnhfk7-ffi-1.17.0-arm64-darwin.gem",
      "stdenv": "/nix/store/jsx4w2b00vzrzxz1fqqhsia4k5a9cnsx-stdenv-darwin",
      "strictDeps": "",
      "suffix": "1.17.0-arm64-darwin",
      "system": "aarch64-darwin",
      "type": "gem",
      "unpackPhase": "runHook preUnpack\n\nif [[ -f $src && $src == *.gem ]]; then\n  if [[ -z \"${dontBuild-}\" ]]; then\n    # we won't know the name of the directory that RubyGems creates,\n    # so we'll just use a glob to find it and move it over.\n    gempkg=\"$src\"\n    sourceRoot=source\n    gem unpack $gempkg --target=container\n    cp -r container/* $sourceRoot\n    rm -r container\n\n    # copy out the original gemspec, for convenience during patching /\n    # overrides.\n    gem specification $gempkg  --ruby > original.gemspec\n    gemspec=$(readlink -f .)/original.gemspec\n  else\n    gempkg=\"$src\"\n  fi\nelse\n  # Fall back to the original thing for everything else.\n  dontBuild=\"\"\n  preUnpack=\"\" postUnpack=\"\" unpackPhase\nfi\n\nrunHook postUnpack\n",
      "version": "1.17.0-arm64-darwin"
    },
    "inputDrvs": {
      "/nix/store/id5mx9d14rsvslg9jklbsqabbd4g1kws-ruby-3.3.4.drv": {
        "dynamicOutputs": {},
        "outputs": [
          "out"
        ]
      },
      "/nix/store/q84ly2pnhlcqliysan6hf085ddprih75-libobjc-11.0.0.drv": {
        "dynamicOutputs": {},
        "outputs": [
          "out"
        ]
      },
      "/nix/store/s8g2d7cjjvrz9lgsbj2qjyc358b7sn0c-stdenv-darwin.drv": {
        "dynamicOutputs": {},
        "outputs": [
          "out"
        ]
      },
      "/nix/store/v0sj121vr9v55wah0jsjd40x4a311mpn-auto-patchelf-hook.drv": {
        "dynamicOutputs": {},
        "outputs": [
          "out"
        ]
      },
      "/nix/store/v1dlxb2q2yncypc3fhhwvk36v0wl3jh1-bash-5.2p32.drv": {
        "dynamicOutputs": {},
        "outputs": [
          "out"
        ]
      },
      "/nix/store/whyak0p0rvmqgr6lwm3gjh5x2sk780qd-make-shell-wrapper-hook.drv": {
        "dynamicOutputs": {},
        "outputs": [
          "out"
        ]
      },
      "/nix/store/y26n0awsg79m2hlp8x7caycmmhd3zh0g-ffi-1.17.0-arm64-darwin.gem.drv": {
        "dynamicOutputs": {},
        "outputs": [
          "out"
        ]
      }
    },
    "inputSrcs": [
      "/nix/store/qjj178v5f2afrzqkp6mvpzsyi1856mf3-gem-post-build.rb",
      "/nix/store/v6x3cs394jgqfbi0a42pam708flxaphh-default-builder.sh"
    ],
    "name": "ruby3.3-ffi-1.17.0-arm64-darwin",
    "outputs": {
      "out": {
        "path": "/nix/store/an5bff2mhkvxlhm5myfrsw4znahp6jvi-ruby3.3-ffi-1.17.0-arm64-darwin"
      }
    },
    "system": "aarch64-darwin"
  }
}
```

**Comment by antoineco** [comment]
The culprit seems to be the last merged patch:
- #46

After pinning `ruby-nix` at the previous revision, the build completes.

**Comment by inscapist** [comment]
thanks for reporting this @antoineco!

I am so silly for overlooking this. autopatchelfhook is only applicable to linux environments. I have added [a commit](https://github.com/inscapist/ruby-nix/commit/5004a3c9f4ac6d32571fde584bff9bc709c7174c) for fixing this. 

Can you try it please? Unfortunately I don't own a mac for replicating this.

**Comment by antoineco** [comment]
@inscapist thanks for the quick fix! I can confirm that the environment builds on macOS at the revision 1f3756f8a713171bf891b39c0d3b1fe6d83a4a63 :+1:

**Comment by inscapist** [comment]
Nice!
